name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Clear Derived Data to prevent build issues
    - name: Clear Derived Data
      run: rm -rf ~/Library/Developer/Xcode/DerivedData

    # Set up Xcode environment
    - name: Set up Xcode
      uses: actions/setup-xcode@v1
      with:
        xcode-version: '14.0' # Match the Xcode version your project requires

    # Install dependencies (if using CocoaPods or Swift Package Manager)
    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies

    # Clean and Build the project
    - name: Clean and Build
      run: |
        xcodebuild clean build \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""

    # Run tests (if available)
    - name: Run Tests
      run: |
        xcodebuild test \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""

    # Enable verbose logging for debugging
    - name: Enable Debug Logging
      run: echo "::set-env name=ACTIONS_STEP_DEBUG::true"
