name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Xcode environment
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v2
      with:
        xcode-version: '15.0' # Update to match your Xcode version

    # Install dependencies (if using CocoaPods or Swift Package Manager)
    # - name: Install dependencies
     # run: |
      #  xcodebuild -resolvePackageDependencies

    # Clean and build the project
    - name: Clean and Build
      run: |
        xcodebuild clean build \
        -workspace RickAndMortyExplorer.xcodeproj \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

    # Run tests (if available)
    - name: Run tests
      run: |
        xcodebuild test \
        -workspace RickAndMortyExplorer.xcodeproj \
        -scheme RickAndMortyExplorer \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
